#!/usr/bin/env sh
. "$(dirname "$0")/_/husky.sh"
#. "$(dirname "$0")/h"
# ./.husky/pre-commit

# Run format and lint
bun run format
# bun run lint

# Automatically add any changes made by formatting and linting
git add .

# git status